language: java
jdk:
- oraclejdk8
dist: trusty
sudo: required

services:
- docker

before_install:
- docker ps -a

# skip the install
install: true

jobs:
  include:
  - stage: build and unit tests
    script:
    - mvn clean install
  - stage: integration tests
    script:
    - mvn -PIT install

cache:
  directories:
  - $HOME/.m2
