language: java
jdk:
- oraclejdk8
dist: trusty
sudo: required

services:
- docker

before_install:
- docker ps -a

# skip the install
install: true

script:
- mvn -PIT clean install

cache:
  directories:
  - $HOME/.m2